name: A basic work flow

on:
#  push:
#    branches: [ "main" ]
      
  
  workflow_dispatch:
  
jobs:
  Dev:
    name: deploy to Dev
    runs-on: ubuntu-latest
      
    steps:
  
      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Install Dependencies
        run: npm install

      - name: Display Name  
        run: echo 'Running on Ubuntu'  

  
  STG:
    name: deploy to STG
    runs-on: macos-latest   
    needs: Dev
  
    steps:
        - name: Install Dependencies
          run: echo 'Running on Mac'
  
  PROD:
      name: deploy to PROD
      runs-on: windows-latest  
   
  
      steps:
        - name: Install Dependencies
          run: echo 'Running on Windows'
  
      