on:
    push:
      branches: 
      - main
      
  
    workflow_dispatch:
  
    jobs:
      Dev:
        name: deploy to Dev
        runs-on: ubuntu-18.04
      
      Steps:
  
        - name: Setup Node
          uses: actions/setup-node@v1
          with:
            node-version: '10.x'
  
        - name: Install Dependencies
          run: npm install
  
        - name: Display Name  
          run: echo 'Running on Ubuntu'  
  
  
    STG:
      name: deploy to STG
      runs-on: macos-latest   
      needs: Dev
  
      Steps:
        - name: Install Dependencies
          run: echo 'Running on Mac'
  
    PROD:
      name: deploy to PROD
      runs-on: windows-latest  
      needs: Dev
  
      Steps:
        - name: Install Dependencies
          run: echo 'Running on Windows'
  
      