name: Environments

on:
  workflow_dispatch:
  
jobs:
  PROD_Deployment:
    runs-on: GA-RUNNER
    environment:
      name: production

    steps:
        - name: display environment
          run: echo "${{ secrets.PROD_SECRET }}"