name: Secrets

on: 
  workflow_dispatch:
  
jobs:
  secrets:
    runs-on: GA-RUNNER
      
    steps:
  
      - name: Print secret
        run: echo "${{ secrets.MY_SECRET }}"

      - name: use as env 
        env:
            secret_value: "${{ secrets.MY_SECRET }}"
        
        run: echo "My env secret value is $secret_value"
